# Generated by Django 2.2.7 on 2019-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0005_auto_20191108_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
